version: '3.8'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dreamview-frontend:dev
    ports:
      - "8081:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../:/app
      - node_modules_cache:/app/node_modules
    command: yarn run start

volumes:
  node_modules_cache:
